apiVersion: v1
kind: Pod
metadata:
  name: postgresql-pod
  labels:
    app: postgresql
spec:
  containers:
  - name: postgresql
    image: bitnami/postgresql:15.3.0-debian-11-r0
    ports:
    - containerPort: 5432
    env:
    - name: POSTGRESQL_USERNAME
      value: "user"
    - name: POSTGRESQL_PASSWORD
      value: "password"
    - name: POSTGRESQL_DATABASE
      value: "mydatabase"
